import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navigation from "@/components/sections/Navigation";

const inter = Inter({ subsets: ["latin"] });
const sans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "The Best Quran App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased min-h-screen flex flex-col",
          inter.className,
          sans.variable
        )}
      >
        <Navigation />
        <div className="flex-1 px-4">{children}</div>
      </body>
    </html>
  );
}
